version: '3.9'
services:
#--------------------------------------------------------------------------------------------------
#   APP DATABASE SERVICE
#--------------------------------------------------------------------------------------------------
  postgres:
    container_name: 'database_container'
    hostname: 'db.iriven.tld'
    image: atchondjo/postgres
    restart: always
    env_file:
      - ./src/settings/.postgres.env
    volumes:
      - ./src/core/postgres/data:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

#--------------------------------------------------------------------------------------------------
#   DATABASES MANAGEMENT SERVICES
#--------------------------------------------------------------------------------------------------
  pgadmin:
    container_name: 'dbadmin_container'
    hostname: 'dbadmin.iriven.tld'
    image: atchondjo/pgadmin4
    restart: always
    ports:
      - 81:80
    env_file:
      - ./src/settings/.pgadmin.env
    volumes:
      - ./src/core/pgadmin:/var/lib/pgadmin
      - ./src/core/pgadmin/log:/var/log/pgadmin
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - postgres

#--------------------------------------------------------------------------------------------------
#   PHP PROCESSING SERVICE
#--------------------------------------------------------------------------------------------------
  php:
    container_name: 'app_container'
    hostname: 'app.iriven.tld'
    restart: always
    build:
      context: ./src/build/php
    expose:
      - '9000'
    volumes:
      - ./src/www/:/var/www/webroot:cached
      - ./src/core/php/log:/var/log
    depends_on:
      - postgres
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    env_file:
      - ./src/settings/.my_app.env
      - ./src/settings/.postgres.env
#--------------------------------------------------------------------------------------------------
#   WEB CLIENT SERVICE
#--------------------------------------------------------------------------------------------------
  nginx:
    container_name: 'gateway_container'
    hostname: 'gw.iriven.tld'
    restart: always
    build:
      context: ./src/build/nginx
    ports:
      - '80:80'
    links: # seems to have no effect alone
      - php
    volumes:
        - ./src/www/:/var/www/webroot:cached
        - ./src/core/nginx/log:/var/log/nginx
    depends_on:
      - php
      - postgres

# # --------------------------------------------------------------------------------------------------
# #   GITLAB-SHELL SERVICE
# # --------------------------------------------------------------------------------------------------
#   gitlabshellserver:
#     image: atchondjo/gitlab-shell:latest
#     restart: always
#     volumes:
#       - ./src/core/gitlab/config/gitlab-shell:/etc/gitlab/gitlab-shell
#       - ./src/core/gitlab/config/ssh:/etc/gitlab/ssh
#       - ./src/core/gitlab/log:/var/log
#       - ssh-authorized-keys:/home/git/.ssh/
#       - sockets:/home/git/run/
#       - gitlab-secret:/etc/gitlab/gitlab-shell/secret

# # --------------------------------------------------------------------------------------------------
# #   REDIS SERVICE
# # --------------------------------------------------------------------------------------------------
#   redisserver:
#     image: atchondjo/redis:latest
#     hostname: 'redis.iriven.tld'
#     restart: always
#     volumes:
#       - ./src/core/gitlab/redis:/data
#     entrypoint: redis-server --appendonly yes

# # --------------------------------------------------------------------------------------------------
# #   GITALY SERVICE
# # --------------------------------------------------------------------------------------------------
#   gitalyserver:
#     image: atchondjo/gitaly:latest
#     init: true
#     restart: always
#     # build:
#     #   context: ./src/build/gitaly
#     depends_on:
#       - gitlabshellserver # for gitlab-secret
#     volumes:
#       - ./src/core/gitlab/repositories:/home/git/repositories
#       - ./src/core/gitlab/config/gitaly/:/etc/gitlab/gitaly
#       - ./src/core/gitlab/config/gitlab-shell:/etc/gitlab/gitlab-shell
#       - ./src/core/gitlab/log/gitaly:/var/log/gitaly
#       - sockets:/home/git/run/
#       - gitlab-secret:/etc/gitlab/gitlab-shell/secret

# #--------------------------------------------------------------------------------------------------
# #   GITLAB WEB SERVICE
# #--------------------------------------------------------------------------------------------------
#   gitlabserver:
#     image: atchondjo/gitlab:latest
#     hostname: 'gitlab.iriven.tld'
#     restart: always
#     # build:
#     #   context: ./src/build/gitlab
#     volumes:
#       - ./src/core/gitlab/repositories:/home/git/repositories
#       - ./src/core/gitlab/config:/etc/gitlab
#       - ./src/core/gitlab/log:/var/log
#       - ./src/core/gitlab/builds:/home/git/gitlab/builds
#       - ./src/core/gitlab/shared:/home/git/gitlab/shared
#       - ./src/core/gitlab/uploads:/home/git/gitlab/public/uploads
#       - ./src/core/gitlab/plugins:/home/git/gitlab/plugins
#       - ./src/core/gitlab/certs/registry:/home/git/certs/registry
#       - ssh-authorized-keys:/home/git/.ssh/
#       - gitlab-secret:/etc/gitlab/gitlab-shell/secret
#       - sockets:/home/git/run/
#     ports:
#       - "2222:22"
#       - "8080:80"
#     depends_on:
#       - postgres
#       - redisserver
#       - gitalyserver
#       - gitlabshellserver
#     env_file:
#       - ./src/settings/.postgres.env
#       - ./src/settings/.gitlab.env
#       - ./src/settings/.registry.env

# # --------------------------------------------------------------------------------------------------
# #   GITLAB REGISTRY SERVICE
# # --------------------------------------------------------------------------------------------------
#   # gitlabrunnerserver:
#   #   image: gitlab/gitlab-runner:alpine
#   #   container_name: gitlab-runner
#   #   restart: always
#   #   depends_on:
#   #     - gitlabserver
#   #   volumes:
#   #     - ./src/core/gitlab/config/gitlab-runner:/etc/gitlab-runner
#   #     - sockets:/var/run/docker.sock
#   #   # networks:
#   #   #   - gitlab

# # --------------------------------------------------------------------------------------------------
# #   GITLAB REGISTRY SERVICE
# # --------------------------------------------------------------------------------------------------
#   registryserver:
#     image: registry:latest
#     ports:
#       - 5001:5000
#     depends_on:
#       - gitlabserver
#     volumes:
#       - ./src/core/gitlab/config/registry:/etc/docker/registry/
#       - ./src/core/gitlab/certs/registry/public:/etc/docker/certs

# #--------------------------------------------------------------------------------------------------
# #   PROJECT VOLUMES LISTING
# #--------------------------------------------------------------------------------------------------
# volumes:
#   sockets:
#   ssh-authorized-keys:
#   gitlab-secret: