version: '3.9'
services:
#--------------------------------------------------------------------------------------------------
#   APP DATABASE SERVICE
#--------------------------------------------------------------------------------------------------
  postgres:
    container_name: dbserver_01
    hostname: dbserver01
    domainname: iriven.tld
    image: atchondjo/postgres
    restart: always
    env_file:
      - ./src/settings/.postgres.env
    volumes:
      - ./src/docker/services/postgres/data:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    # networks:
    #   - vpcdbase

#--------------------------------------------------------------------------------------------------
#   DATABASES MANAGEMENT SERVICES
#--------------------------------------------------------------------------------------------------
  pgadmin:
    container_name: dbserveradm_01
    hostname: dbserveradm01
    domainname: iriven.tld
    image: atchondjo/pgadmin4
    restart: always
    ports:
      - 81:80
    env_file:
      - ./src/settings/.pgadmin.env
    volumes:
      - ./src/docker/services/pgadmin:/var/lib/pgadmin
      - ./src/docker/services/pgadmin/log:/var/log/pgadmin
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - postgres
    # networks:
    #   - vpcdbase

#--------------------------------------------------------------------------------------------------
#   PHP PROCESSING SERVICE
#--------------------------------------------------------------------------------------------------
  php:
    container_name: webserver_01
    hostname: webserver01
    domainname: iriven.tld
    restart: always
    build:
      context: ./src/docker/infra/php
    expose:
      - 9000
    volumes:
      - ./src/www/:/var/www/webroot:cached
      - ./src/docker/services/php/log:/var/log
    depends_on:
      - postgres
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    env_file:
      - ./src/settings/.my_app.env
      - ./src/settings/.postgres.env
    # networks:
    #   # you may set custom IP addresses
    #   - vpcprod
    #   - vpcdbase
#--------------------------------------------------------------------------------------------------
#   WEB CLIENT SERVICE
#--------------------------------------------------------------------------------------------------
  nginx:
    container_name: proxyserver_01
    hostname: proxyserver01
    domainname: iriven.tld
    restart: always
    build:
      context: ./src/docker/infra/nginx
    ports:
      - '80:80'
    links: # seems to have no effect alone
      - php
    volumes:
        - ./src/www/:/var/www/webroot:cached
        - ./src/docker/services/nginx/log:/var/log/nginx
    depends_on:
      - php
      - postgres
    # networks:
    #   - vpcshared
    #   - vpcprod

#--------------------------------------------------------------------------------------------------
#   PROJECT VOLUMES LISTING
#--------------------------------------------------------------------------------------------------
# volumes:
#   pgadminvol:
#   ssh-authorized-keys:
#   gitlab-secret:

#--------------------------------------------------------------------------------------------------
#   DOCKER CONTAINERS NETWORK LISTING
#--------------------------------------------------------------------------------------------------
# networks:
#   vpcshared:
#     # use the bridge driver, but enable IPv6
#     driver: bridge
#     driver_opts:
#       com.docker.network.enable_ipv6: "true"
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.16.238.0/24
#           gateway: 172.16.238.1
#         - subnet: "2001:3984:3989::/64"
#           gateway: "2001:3984:3989::1"
#   vpcprod:
#     # use a custom driver, with no options
#     driver: overlay
#     attachable: true
#     driver_opts:
#       com.docker.network.enable_ipv6: "true"
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.17.235.0/24
#           gateway: 172.17.235.1
#         - subnet: "2004:3981:3989::/64"
#           gateway: "2004:3981:3989::1"
#   vpcdbase:
#     # use a custom driver, with no options
#     driver: overlay
#     attachable: true
#     driver_opts:
#       com.docker.network.enable_ipv6: "true"
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.10.212.0/24
#           gateway: 172.10.212.1
#         - subnet: "2002:3086:3989::/64"
#           gateway: "2002:3086:3989::1"
